version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: lint
          command: npm run lint
      - run:
          name: build
          command: npm run build
workflows:
  test:
    jobs:
      - test
